import type { Act2Item } from "./types";
import type { Construct, InteractionElementType } from "@/generated/prisma/client";

/**
 * V2 Item Bank: 86 items across 5 constructs for Act 2 adaptive investigation loops.
 *
 * Each item has calibrated difficulty (1-5) and timing expectations.
 * Items are selected adaptively based on the candidate's performance.
 */

// ──────────────────────────────────────────────
// QUANTITATIVE REASONING (20 items)
// ──────────────────────────────────────────────

const QUANTITATIVE_REASONING_ITEMS: Act2Item[] = [
  // Easy (5 items)
  { id: "qr-e1", construct: "QUANTITATIVE_REASONING" as Construct, subType: "arithmetic", difficulty: 0.2, difficultyLevel: 1, prompt: "A project has a budget of $45,000. If 3 phases each use $12,500, how much budget remains?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "7500", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },
  { id: "qr-e2", construct: "QUANTITATIVE_REASONING" as Construct, subType: "percentage", difficulty: 0.2, difficultyLevel: 1, prompt: "A team of 40 people has a 15% absentee rate today. How many people are present?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "34", timingExpectations: { fast: 10000, typical: 20000, slow: 35000 } },
  { id: "qr-e3", construct: "QUANTITATIVE_REASONING" as Construct, subType: "ratio", difficulty: 0.25, difficultyLevel: 1, prompt: "If a machine processes 180 units in 3 hours, how many units does it process per hour?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "60", timingExpectations: { fast: 8000, typical: 15000, slow: 25000 } },
  { id: "qr-e4", construct: "QUANTITATIVE_REASONING" as Construct, subType: "arithmetic", difficulty: 0.25, difficultyLevel: 1, prompt: "A warehouse receives 3 shipments: 450 units, 280 units, and 670 units. What is the total inventory added?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "1400", timingExpectations: { fast: 8000, typical: 12000, slow: 25000 } },
  { id: "qr-e5", construct: "QUANTITATIVE_REASONING" as Construct, subType: "percentage", difficulty: 0.3, difficultyLevel: 1, prompt: "An order of 200 items has a 5% defect rate. How many items are defective?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "10", timingExpectations: { fast: 8000, typical: 15000, slow: 25000 } },

  // Medium (8 items)
  { id: "qr-m1", construct: "QUANTITATIVE_REASONING" as Construct, subType: "multi-step", difficulty: 0.45, difficultyLevel: 2, prompt: "A company spends $24,000/month on supplies. They negotiate a 12% discount. How much do they save per year?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "34560", timingExpectations: { fast: 15000, typical: 30000, slow: 60000 } },
  { id: "qr-m2", construct: "QUANTITATIVE_REASONING" as Construct, subType: "rate", difficulty: 0.45, difficultyLevel: 2, prompt: "Worker A completes a task in 6 hours. Worker B completes the same task in 4 hours. If they work together, approximately how many hours will it take?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "2.4", timingExpectations: { fast: 20000, typical: 40000, slow: 75000 } },
  { id: "qr-m3", construct: "QUANTITATIVE_REASONING" as Construct, subType: "comparison", difficulty: 0.5, difficultyLevel: 3, prompt: "Plan A costs $800/month with a $2,000 setup fee. Plan B costs $950/month with no setup fee. After how many months does Plan A become cheaper?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "14", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
  { id: "qr-m4", construct: "QUANTITATIVE_REASONING" as Construct, subType: "percentage", difficulty: 0.5, difficultyLevel: 3, prompt: "A product's price increases by 20%, then is discounted by 20%. If the original price was $100, what is the final price?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "96", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "qr-m5", construct: "QUANTITATIVE_REASONING" as Construct, subType: "weighted-avg", difficulty: 0.55, difficultyLevel: 3, prompt: "A team of 5 people scored 78, 85, 92, 68, and 77 on a test. What is the team average?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "80", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "qr-m6", construct: "QUANTITATIVE_REASONING" as Construct, subType: "multi-step", difficulty: 0.55, difficultyLevel: 3, prompt: "A factory produces 1,200 units/day. Monday: 2% defect rate. Tuesday: 3.5% defect rate. How many total non-defective units were produced over both days?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "2334", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "qr-m7", construct: "QUANTITATIVE_REASONING" as Construct, subType: "proportion", difficulty: 0.6, difficultyLevel: 3, prompt: "If 3 machines take 8 hours to complete a job, how many hours would 5 machines take (assuming equal productivity)?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "4.8", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "qr-m8", construct: "QUANTITATIVE_REASONING" as Construct, subType: "algebraic", difficulty: 0.6, difficultyLevel: 3, prompt: "A company needs to ship 500 packages. Large boxes hold 12, small boxes hold 5. Using 30 large boxes, how many small boxes are needed for the remainder?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "28", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },

  // Hard (7 items)
  { id: "qr-h1", construct: "QUANTITATIVE_REASONING" as Construct, subType: "multi-variable", difficulty: 0.7, difficultyLevel: 4, prompt: "Overtime costs $45/hr for the first 10 hours and $60/hr after. A worker did 18 hours of overtime. What is the total overtime pay?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "930", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "qr-h2", construct: "QUANTITATIVE_REASONING" as Construct, subType: "probability", difficulty: 0.75, difficultyLevel: 4, prompt: "A quality test catches 90% of defective items. If 5% of all items are defective, what percentage of items that PASS the test are actually defective?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "0.52", timingExpectations: { fast: 40000, typical: 75000, slow: 120000 } },
  { id: "qr-h3", construct: "QUANTITATIVE_REASONING" as Construct, subType: "optimization", difficulty: 0.75, difficultyLevel: 4, prompt: "Shipping costs $200 base + $3/kg. Insurance costs 4% of goods value. A 150kg shipment worth $8,000 needs both. What is the total cost?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "970", timingExpectations: { fast: 30000, typical: 60000, slow: 100000 } },
  { id: "qr-h4", construct: "QUANTITATIVE_REASONING" as Construct, subType: "compound", difficulty: 0.8, difficultyLevel: 4, prompt: "An investment earns 6% annually compounded. Starting with $10,000, approximately how much will there be after 3 years? Round to the nearest dollar.", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "11910", timingExpectations: { fast: 30000, typical: 65000, slow: 120000 } },
  { id: "qr-h5", construct: "QUANTITATIVE_REASONING" as Construct, subType: "systems", difficulty: 0.85, difficultyLevel: 5, prompt: "Three departments share a budget of $100,000. Dept A gets twice what Dept C gets. Dept B gets $10,000 more than Dept C. How much does Dept A get?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "45000", timingExpectations: { fast: 35000, typical: 70000, slow: 120000 } },
  { id: "qr-h6", construct: "QUANTITATIVE_REASONING" as Construct, subType: "rate-change", difficulty: 0.85, difficultyLevel: 5, prompt: "A process takes 20 minutes the first time. Each repetition is 8% faster than the previous one. How many minutes does the 4th repetition take? Round to 1 decimal.", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "15.6", timingExpectations: { fast: 40000, typical: 80000, slow: 150000 } },
  { id: "qr-h7", construct: "QUANTITATIVE_REASONING" as Construct, subType: "multi-variable", difficulty: 0.9, difficultyLevel: 5, prompt: "A tank fills at 50L/min and drains at 20L/min simultaneously. Starting empty (capacity 900L), how many minutes until full?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "30", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
];

// ──────────────────────────────────────────────
// SPATIAL VISUALIZATION (18 items)
// ──────────────────────────────────────────────

const SPATIAL_VISUALIZATION_ITEMS: Act2Item[] = [
  // Easy (4 items)
  { id: "sv-e1", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "rotation", difficulty: 0.2, difficultyLevel: 1, prompt: "Imagine the letter 'F' rotated 90° clockwise. Which of these matches?\nA) ⌐\nB) Γ\nC) ⌡\nD) ┘", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 10000, typical: 20000, slow: 40000 } },
  { id: "sv-e2", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "counting", difficulty: 0.25, difficultyLevel: 1, prompt: "A cube is made of 27 smaller cubes (3×3×3). If you remove all the corner cubes, how many small cubes remain?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "19", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "sv-e3", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "folding", difficulty: 0.3, difficultyLevel: 1, prompt: "A flat cross-shaped piece of paper (+) is folded into a box without a lid. How many faces does the box have?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "5", timingExpectations: { fast: 10000, typical: 20000, slow: 40000 } },
  { id: "sv-e4", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "perspective", difficulty: 0.3, difficultyLevel: 1, prompt: "You are looking at a cylinder from directly above. What shape do you see?\nA) Rectangle\nB) Circle\nC) Oval\nD) Triangle", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },

  // Medium (7 items)
  { id: "sv-m1", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "rotation", difficulty: 0.45, difficultyLevel: 2, prompt: "If you rotate the number '6' by 180°, you get '9'. What do you get if you rotate the sequence '86' by 180°?\nA) 89\nB) 98\nC) 68\nD) 96", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 25000, slow: 50000 } },
  { id: "sv-m2", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "cross-section", difficulty: 0.5, difficultyLevel: 3, prompt: "You slice a cube diagonally from one top edge to the opposite bottom edge. What shape is the cross-section?\nA) Square\nB) Triangle\nC) Rectangle\nD) Hexagon", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "sv-m3", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "counting", difficulty: 0.5, difficultyLevel: 3, prompt: "A staircase is built from blocks: row 1 has 1 block, row 2 has 2 blocks, row 3 has 3 blocks, up to row 6. How many blocks total?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "21", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "sv-m4", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "assembly", difficulty: 0.55, difficultyLevel: 3, prompt: "You have 4 identical right-angle triangles. Can you arrange them to form a square?\nA) Yes, with no gaps or overlaps\nB) Yes, but with a square hole in the middle\nC) No, it's impossible\nD) Only if the triangles are isoceles", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "sv-m5", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "mirror", difficulty: 0.55, difficultyLevel: 3, prompt: "The word 'AMBULANCE' is often printed as a mirror image on the front of the vehicle. If you look at it in your rearview mirror, it appears normal. What would the mirror image of 'BED' look like?\nA) BED\nB) DEB\nC) BƎD\nD) ᗺƎᗡ", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "D", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "sv-m6", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "volume", difficulty: 0.6, difficultyLevel: 3, prompt: "A rectangular tank is 2m × 3m × 4m. If it's filled to 75% capacity, how many cubic meters of water does it contain?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "18", timingExpectations: { fast: 15000, typical: 30000, slow: 60000 } },
  { id: "sv-m7", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "unfolding", difficulty: 0.6, difficultyLevel: 3, prompt: "A piece of paper is folded in half, then in half again. A single hole is punched through all layers. When unfolded, how many holes are there?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "4", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },

  // Hard (7 items)
  { id: "sv-h1", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "rotation-3d", difficulty: 0.7, difficultyLevel: 4, prompt: "A die has 1 on top and 2 facing you. If you tip it forward (away from you), what number is now on top?\nA) 5\nB) 3\nC) 6\nD) 4", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
  { id: "sv-h2", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "cross-section", difficulty: 0.75, difficultyLevel: 4, prompt: "You slice a cone with a plane that is NOT parallel to the base and does NOT pass through the apex. What shape is the cross-section?\nA) Circle\nB) Ellipse\nC) Triangle\nD) Parabola", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
  { id: "sv-h3", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "net-folding", difficulty: 0.75, difficultyLevel: 4, prompt: "How many distinct nets (flat patterns) can fold into a cube?\nA) 6\nB) 8\nC) 11\nD) 15", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 20000, typical: 50000, slow: 90000 } },
  { id: "sv-h4", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "surface-area", difficulty: 0.8, difficultyLevel: 4, prompt: "A 3×3×3 cube is painted red on all sides, then cut into 27 unit cubes. How many unit cubes have exactly 2 red faces?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "12", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "sv-h5", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "transformation", difficulty: 0.8, difficultyLevel: 5, prompt: "A shape is reflected across a vertical axis, then rotated 90° clockwise. This is equivalent to:\nA) A 90° counterclockwise rotation then reflection\nB) A single reflection across a different axis\nC) A 180° rotation\nD) None of the above — order matters", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 30000, typical: 60000, slow: 100000 } },
  { id: "sv-h6", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "packing", difficulty: 0.85, difficultyLevel: 5, prompt: "What is the maximum number of 1×1×1 cubes that fit inside a sphere with a diameter of 3?\nA) 8\nB) 12\nC) 14\nD) 16", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 30000, typical: 60000, slow: 100000 } },
  { id: "sv-h7", construct: "SPATIAL_VISUALIZATION" as Construct, subType: "projection", difficulty: 0.9, difficultyLevel: 5, prompt: "An L-shaped 3D piece (like a Tetris L) is viewed from the front, side, and top. Which views are identical?\nA) Front and Side only\nB) Front and Top only\nC) Side and Top only\nD) All three are different", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "D", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
];

// ──────────────────────────────────────────────
// MECHANICAL REASONING (15 items)
// ──────────────────────────────────────────────

const MECHANICAL_REASONING_ITEMS: Act2Item[] = [
  { id: "mr-e1", construct: "MECHANICAL_REASONING" as Construct, subType: "gears", difficulty: 0.2, difficultyLevel: 1, prompt: "Two gears are meshed together. If the first gear turns clockwise, which direction does the second gear turn?\nA) Clockwise\nB) Counterclockwise\nC) It doesn't turn\nD) It depends on the size", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },
  { id: "mr-e2", construct: "MECHANICAL_REASONING" as Construct, subType: "levers", difficulty: 0.25, difficultyLevel: 1, prompt: "A seesaw has a heavy person on one end. To balance, should the lighter person sit closer to or farther from the center?\nA) Closer to the center\nB) Farther from the center\nC) It doesn't matter\nD) They need to be the same distance", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },
  { id: "mr-e3", construct: "MECHANICAL_REASONING" as Construct, subType: "pulleys", difficulty: 0.3, difficultyLevel: 1, prompt: "A single fixed pulley changes the direction of force. Does it reduce the amount of force needed to lift a load?\nA) Yes, by half\nB) Yes, significantly\nC) No, it only changes direction\nD) Only if the rope is longer", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 10000, typical: 20000, slow: 35000 } },
  { id: "mr-e4", construct: "MECHANICAL_REASONING" as Construct, subType: "pressure", difficulty: 0.3, difficultyLevel: 1, prompt: "You can push a thumbtack into a board but not a flat-headed nail of the same weight. Why?\nA) The thumbtack is sharper (smaller area = more pressure)\nB) The thumbtack is made of softer metal\nC) The flat head absorbs more force\nD) The board material matters more", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 10000, typical: 20000, slow: 35000 } },
  { id: "mr-m1", construct: "MECHANICAL_REASONING" as Construct, subType: "gears", difficulty: 0.45, difficultyLevel: 2, prompt: "A gear with 20 teeth drives a gear with 40 teeth. If the smaller gear makes 100 RPM, how fast does the larger gear turn?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "50", timingExpectations: { fast: 15000, typical: 30000, slow: 55000 } },
  { id: "mr-m2", construct: "MECHANICAL_REASONING" as Construct, subType: "levers", difficulty: 0.5, difficultyLevel: 3, prompt: "A lever arm is 2m long with the fulcrum 0.5m from one end. A 100kg weight sits on the short end. What weight on the long end would balance it?\nA) 25kg\nB) 33.3kg\nC) 50kg\nD) 75kg", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "mr-m3", construct: "MECHANICAL_REASONING" as Construct, subType: "hydraulics", difficulty: 0.5, difficultyLevel: 3, prompt: "In a hydraulic system, a small piston (area 2 cm²) pushes with 50N. The large piston has area 20 cm². What force does the large piston exert?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "500", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "mr-m4", construct: "MECHANICAL_REASONING" as Construct, subType: "fluids", difficulty: 0.55, difficultyLevel: 3, prompt: "Two identical pipes carry water. Pipe A has twice the water pressure of Pipe B. Which has a higher flow rate?\nA) Pipe A (higher pressure = more flow)\nB) Pipe B\nC) Equal flow\nD) Cannot determine without pipe diameter", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 15000, typical: 30000, slow: 55000 } },
  { id: "mr-m5", construct: "MECHANICAL_REASONING" as Construct, subType: "energy", difficulty: 0.55, difficultyLevel: 3, prompt: "A ball is dropped from 10m. Ignoring air resistance, at 5m height, its kinetic energy is:\nA) Zero\nB) 25% of total energy\nC) 50% of total energy\nD) 75% of total energy", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "mr-m6", construct: "MECHANICAL_REASONING" as Construct, subType: "pulleys", difficulty: 0.6, difficultyLevel: 3, prompt: "A system has 4 pulleys (2 fixed, 2 movable) supporting a 400N load. What force is needed to hold it (ignoring friction)?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "100", timingExpectations: { fast: 20000, typical: 45000, slow: 75000 } },
  { id: "mr-h1", construct: "MECHANICAL_REASONING" as Construct, subType: "gear-train", difficulty: 0.7, difficultyLevel: 4, prompt: "Three gears in sequence: A (10 teeth) → B (30 teeth) → C (15 teeth). If A turns at 300 RPM clockwise, what speed and direction does C turn?\nA) 200 RPM clockwise\nB) 200 RPM counterclockwise\nC) 100 RPM clockwise\nD) 600 RPM counterclockwise", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "mr-h2", construct: "MECHANICAL_REASONING" as Construct, subType: "structural", difficulty: 0.75, difficultyLevel: 4, prompt: "A triangular truss is more rigid than a rectangular frame because:\nA) Triangles distribute weight to the ground\nB) Triangles cannot deform without changing side lengths\nC) The angles in a triangle are stronger\nD) Rectangles have more joints to fail", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "mr-h3", construct: "MECHANICAL_REASONING" as Construct, subType: "thermodynamics", difficulty: 0.75, difficultyLevel: 4, prompt: "A metal rod is heated at one end. Heat conducts to the other end. If the rod is twice as long, the time for the other end to reach the same temperature:\nA) Doubles\nB) Quadruples\nC) Stays the same\nD) Halves", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
  { id: "mr-h4", construct: "MECHANICAL_REASONING" as Construct, subType: "mechanical-advantage", difficulty: 0.8, difficultyLevel: 5, prompt: "A screw has 8 threads per centimeter. A wrench 20cm long turns it. If you apply 10N at the wrench handle, approximately what axial force does the screw exert?\nA) 80N\nB) 500N\nC) 1,005N\nD) 5,027N", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 30000, typical: 60000, slow: 100000 } },
  { id: "mr-h5", construct: "MECHANICAL_REASONING" as Construct, subType: "systems", difficulty: 0.85, difficultyLevel: 5, prompt: "In a car engine, the crankshaft converts linear piston motion to rotary motion. If a 4-cylinder engine fires in the order 1-3-4-2, why isn't it 1-2-3-4?\nA) To balance vibration forces\nB) To allow proper exhaust timing\nC) Manufacturing is simpler\nD) Fuel injection requires alternating cylinders", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
];

// ──────────────────────────────────────────────
// PATTERN RECOGNITION (18 items)
// ──────────────────────────────────────────────

const PATTERN_RECOGNITION_ITEMS: Act2Item[] = [
  { id: "pr-e1", construct: "PATTERN_RECOGNITION" as Construct, subType: "number-sequence", difficulty: 0.2, difficultyLevel: 1, prompt: "What comes next: 2, 4, 6, 8, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "10", timingExpectations: { fast: 5000, typical: 10000, slow: 20000 } },
  { id: "pr-e2", construct: "PATTERN_RECOGNITION" as Construct, subType: "number-sequence", difficulty: 0.25, difficultyLevel: 1, prompt: "What comes next: 3, 6, 12, 24, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "48", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },
  { id: "pr-e3", construct: "PATTERN_RECOGNITION" as Construct, subType: "letter-sequence", difficulty: 0.25, difficultyLevel: 1, prompt: "What comes next: A, C, E, G, ___?\nA) H\nB) I\nC) J\nD) K", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A) H", "B) I", "C) J", "D) K"], correctAnswer: "B) I", timingExpectations: { fast: 8000, typical: 15000, slow: 25000 } },
  { id: "pr-e4", construct: "PATTERN_RECOGNITION" as Construct, subType: "visual", difficulty: 0.3, difficultyLevel: 1, prompt: "In a 3×3 grid, each row has a circle, square, and triangle. Each row has red, blue, green. Row 3 has a blue circle and green square. What is the missing shape and color?\nA) Red triangle\nB) Green triangle\nC) Red square\nD) Blue square", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "pr-m1", construct: "PATTERN_RECOGNITION" as Construct, subType: "number-sequence", difficulty: 0.45, difficultyLevel: 2, prompt: "What comes next: 1, 1, 2, 3, 5, 8, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "13", timingExpectations: { fast: 10000, typical: 20000, slow: 40000 } },
  { id: "pr-m2", construct: "PATTERN_RECOGNITION" as Construct, subType: "number-sequence", difficulty: 0.5, difficultyLevel: 3, prompt: "What comes next: 1, 4, 9, 16, 25, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "36", timingExpectations: { fast: 10000, typical: 20000, slow: 40000 } },
  { id: "pr-m3", construct: "PATTERN_RECOGNITION" as Construct, subType: "alternating", difficulty: 0.5, difficultyLevel: 3, prompt: "What comes next: 2, 5, 3, 6, 4, 7, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "5", timingExpectations: { fast: 15000, typical: 30000, slow: 55000 } },
  { id: "pr-m4", construct: "PATTERN_RECOGNITION" as Construct, subType: "data-pattern", difficulty: 0.55, difficultyLevel: 3, prompt: "Weekly sales: Mon 100, Tue 120, Wed 110, Thu 130, Fri 120, Mon 110, Tue 130, Wed 120, Thu 140. What is the most likely value for Friday?\nA) 120\nB) 130\nC) 140\nD) 150", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "pr-m5", construct: "PATTERN_RECOGNITION" as Construct, subType: "rule-discovery", difficulty: 0.55, difficultyLevel: 3, prompt: "Input → Output: 3 → 7, 5 → 11, 8 → 17, 12 → 25. What is the rule?\nA) Multiply by 2, add 1\nB) Multiply by 3, subtract 2\nC) Add 4\nD) Square, then subtract 2", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 20000, typical: 40000, slow: 70000 } },
  { id: "pr-m6", construct: "PATTERN_RECOGNITION" as Construct, subType: "matrix", difficulty: 0.6, difficultyLevel: 3, prompt: "In a number grid:\n2 4 6\n3 6 9\n4 8 ?\nWhat replaces the ?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "12", timingExpectations: { fast: 10000, typical: 25000, slow: 45000 } },
  { id: "pr-m7", construct: "PATTERN_RECOGNITION" as Construct, subType: "geometric", difficulty: 0.6, difficultyLevel: 3, prompt: "A pattern adds one more side each step: triangle (3), square (4), pentagon (5). What is the interior angle of the 5th shape (heptagon, 7 sides)? Round to the nearest degree.", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "129", timingExpectations: { fast: 25000, typical: 50000, slow: 80000 } },
  { id: "pr-h1", construct: "PATTERN_RECOGNITION" as Construct, subType: "complex-sequence", difficulty: 0.7, difficultyLevel: 4, prompt: "What comes next: 1, 3, 7, 15, 31, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "63", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "pr-h2", construct: "PATTERN_RECOGNITION" as Construct, subType: "data-anomaly", difficulty: 0.7, difficultyLevel: 4, prompt: "Monthly production: Jan 1000, Feb 1050, Mar 1100, Apr 980, May 1150, Jun 1200, Jul 1100, Aug 1250. Which month likely had an anomaly?\nA) February\nB) April\nC) July\nD) August", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "pr-h3", construct: "PATTERN_RECOGNITION" as Construct, subType: "nested-pattern", difficulty: 0.75, difficultyLevel: 4, prompt: "What comes next: 2, 3, 5, 7, 11, 13, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "17", timingExpectations: { fast: 10000, typical: 25000, slow: 50000 } },
  { id: "pr-h4", construct: "PATTERN_RECOGNITION" as Construct, subType: "multi-rule", difficulty: 0.75, difficultyLevel: 4, prompt: "Employees A-E are seated around a table. A is next to B. C is across from A. D is not next to E. B is next to C. Where is E seated?\nA) Next to A and D\nB) Next to C and D\nC) Next to A and C\nD) Next to D only", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 30000, typical: 60000, slow: 100000 } },
  { id: "pr-h5", construct: "PATTERN_RECOGNITION" as Construct, subType: "abstract-series", difficulty: 0.8, difficultyLevel: 5, prompt: "What comes next: 1, 11, 21, 1211, 111221, ___?\nA) 312211\nB) 122211\nC) 212221\nD) 111222", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 30000, typical: 60000, slow: 120000 } },
  { id: "pr-h6", construct: "PATTERN_RECOGNITION" as Construct, subType: "correlation", difficulty: 0.85, difficultyLevel: 5, prompt: "Datasets X and Y:\nX: 10, 20, 30, 40, 50\nY: 95, 85, 75, 65, 55\nWhat type of relationship exists?\nA) Perfect positive correlation\nB) Perfect negative correlation\nC) No correlation\nD) Non-linear correlation", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "pr-h7", construct: "PATTERN_RECOGNITION" as Construct, subType: "meta-pattern", difficulty: 0.9, difficultyLevel: 5, prompt: "What comes next: 0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, ___?", elementType: "NUMERIC_INPUT" as InteractionElementType, correctAnswer: "4", timingExpectations: { fast: 40000, typical: 80000, slow: 150000 } },
];

// ──────────────────────────────────────────────
// FLUID REASONING (15 items)
// ──────────────────────────────────────────────

const FLUID_REASONING_ITEMS: Act2Item[] = [
  { id: "fr-e1", construct: "FLUID_REASONING" as Construct, subType: "analogy", difficulty: 0.2, difficultyLevel: 1, prompt: "Hot is to Cold as Fast is to:\nA) Quick\nB) Slow\nC) Run\nD) Speed", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 5000, typical: 12000, slow: 25000 } },
  { id: "fr-e2", construct: "FLUID_REASONING" as Construct, subType: "deduction", difficulty: 0.25, difficultyLevel: 1, prompt: "All managers attend the meeting. Sarah is a manager. Therefore:\nA) Sarah might attend\nB) Sarah attends the meeting\nC) Sarah leads the meeting\nD) Cannot determine", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 8000, typical: 15000, slow: 30000 } },
  { id: "fr-e3", construct: "FLUID_REASONING" as Construct, subType: "classification", difficulty: 0.25, difficultyLevel: 1, prompt: "Which item does NOT belong: hammer, screwdriver, wrench, banana?\nA) Hammer\nB) Screwdriver\nC) Wrench\nD) Banana", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "D", timingExpectations: { fast: 5000, typical: 10000, slow: 20000 } },
  { id: "fr-e4", construct: "FLUID_REASONING" as Construct, subType: "analogy", difficulty: 0.3, difficultyLevel: 1, prompt: "Surgeon is to Scalpel as Carpenter is to:\nA) Wood\nB) Hammer\nC) House\nD) Blueprint", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 8000, typical: 15000, slow: 25000 } },
  { id: "fr-m1", construct: "FLUID_REASONING" as Construct, subType: "conditional", difficulty: 0.45, difficultyLevel: 2, prompt: "If it rains, the event moves indoors. The event was held outdoors. What can you conclude?\nA) It did not rain\nB) It might have rained\nC) The organizers ignored the rule\nD) Cannot determine", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 12000, typical: 25000, slow: 45000 } },
  { id: "fr-m2", construct: "FLUID_REASONING" as Construct, subType: "syllogism", difficulty: 0.5, difficultyLevel: 3, prompt: "Some engineers are managers. All managers attend training. Which MUST be true?\nA) All engineers attend training\nB) Some engineers attend training\nC) No engineers attend training\nD) All who attend training are engineers", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "fr-m3", construct: "FLUID_REASONING" as Construct, subType: "analogy-complex", difficulty: 0.55, difficultyLevel: 3, prompt: "Input is to Process as Seed is to:\nA) Plant\nB) Soil\nC) Growth\nD) Sunlight", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 12000, typical: 25000, slow: 45000 } },
  { id: "fr-m4", construct: "FLUID_REASONING" as Construct, subType: "inductive", difficulty: 0.55, difficultyLevel: 3, prompt: "In City X, crime decreased after streetlights were installed. In City Y, crime also decreased after streetlights. The STRONGEST conclusion:\nA) Streetlights definitely reduce crime\nB) There is evidence streetlights may reduce crime\nC) Installing lights everywhere will eliminate crime\nD) The decrease was coincidental", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 15000, typical: 30000, slow: 50000 } },
  { id: "fr-m5", construct: "FLUID_REASONING" as Construct, subType: "matrix", difficulty: 0.6, difficultyLevel: 3, prompt: "In a logic grid: A is taller than B. C is shorter than B. D is taller than A. Rank from tallest to shortest.\nA) D, A, B, C\nB) D, A, C, B\nC) A, D, B, C\nD) D, B, A, C", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "A", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "fr-m6", construct: "FLUID_REASONING" as Construct, subType: "causal", difficulty: 0.6, difficultyLevel: 3, prompt: "Sales increased when ads were changed AND the price was lowered simultaneously. What is the most defensible conclusion?\nA) The new ads caused increased sales\nB) The price drop caused increased sales\nC) We cannot attribute the increase to either factor alone\nD) Both factors contributed equally", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "C", timingExpectations: { fast: 15000, typical: 30000, slow: 55000 } },
  { id: "fr-h1", construct: "FLUID_REASONING" as Construct, subType: "multi-step", difficulty: 0.7, difficultyLevel: 4, prompt: "If all X are Y, and some Y are Z, and no Z are W, which MUST be true?\nA) No X are W\nB) Some X are Z\nC) Some X are not W\nD) None of these must be true", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "D", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "fr-h2", construct: "FLUID_REASONING" as Construct, subType: "paradox", difficulty: 0.75, difficultyLevel: 4, prompt: "A company that laid off 20% of workers saw productivity INCREASE by 5%. The BEST explanation:\nA) The remaining workers worked harder out of fear\nB) The least productive workers were laid off\nC) The layoff eliminated redundancies\nD) All are plausible; we need more data to distinguish", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "D", timingExpectations: { fast: 15000, typical: 35000, slow: 60000 } },
  { id: "fr-h3", construct: "FLUID_REASONING" as Construct, subType: "abstract-reasoning", difficulty: 0.8, difficultyLevel: 4, prompt: "In a system: A causes B. B inhibits C. C enables D. If A is removed, what happens to D?\nA) D stops (A→B→¬C→¬D)\nB) D starts (no A→no B→C runs→D)\nC) D is unaffected\nD) Cannot determine without knowing D's default state", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 25000, typical: 50000, slow: 90000 } },
  { id: "fr-h4", construct: "FLUID_REASONING" as Construct, subType: "counter-argument", difficulty: 0.85, difficultyLevel: 5, prompt: "Argument: 'We should hire only candidates with 5+ years experience because our top performers all have 5+ years.' The STRONGEST counter-argument:\nA) Experience doesn't guarantee performance\nB) We never hired people with less experience, so we can't know their potential\nC) Some experienced candidates also underperform\nD) Industry norms suggest 3 years is sufficient", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
  { id: "fr-h5", construct: "FLUID_REASONING" as Construct, subType: "systems-thinking", difficulty: 0.9, difficultyLevel: 5, prompt: "A hospital reduces ER wait times by hiring more doctors. Wait times drop, but patient satisfaction scores also drop. The MOST likely explanation:\nA) New doctors are less skilled\nB) Faster processing means less doctor-patient interaction time\nC) Patients preferred the old doctors\nD) The measurement methodology changed", elementType: "MULTIPLE_CHOICE_INLINE" as InteractionElementType, options: ["A", "B", "C", "D"], correctAnswer: "B", timingExpectations: { fast: 20000, typical: 45000, slow: 80000 } },
];

// ──────────────────────────────────────────────
// Full item bank index
// ──────────────────────────────────────────────

export const ITEM_BANK: Act2Item[] = [
  ...QUANTITATIVE_REASONING_ITEMS,
  ...SPATIAL_VISUALIZATION_ITEMS,
  ...MECHANICAL_REASONING_ITEMS,
  ...PATTERN_RECOGNITION_ITEMS,
  ...FLUID_REASONING_ITEMS,
];

/**
 * Get items for a specific construct, sorted by difficulty.
 */
export function getItemsForConstruct(construct: string): Act2Item[] {
  return ITEM_BANK
    .filter((item) => item.construct === construct)
    .sort((a, b) => a.difficulty - b.difficulty);
}

/**
 * Get items by difficulty range for a construct, excluding already-served items.
 */
export function getAvailableItems(
  construct: string,
  minDifficulty: number,
  maxDifficulty: number,
  excludeIds: string[],
): Act2Item[] {
  const excluded = new Set(excludeIds);
  return ITEM_BANK
    .filter(
      (item) =>
        item.construct === construct &&
        item.difficulty >= minDifficulty &&
        item.difficulty <= maxDifficulty &&
        !excluded.has(item.id),
    )
    .sort((a, b) => a.difficulty - b.difficulty);
}
