/**
 * F8: PARALLEL_SCENARIO TurnBuilder — Act 3 Phase 2.
 * Identical flow to F2 (Open Probe) but in Act 3 for consistency checking.
 */
import type { TurnBuilderContext } from "./context";
import type { AssessmentTurnResponse } from "@/lib/types/turn";
import { buildOpenProbe } from "./open-probe";

export async function buildParallelScenario(ctx: TurnBuilderContext): Promise<AssessmentTurnResponse> {
  // Parallel scenarios must ALWAYS be generated by Haiku using the engine's custom
  // systemPrompt (which embeds the source scenario context). We must never serve
  // pre-generated Act 1 beat content here — strip contentLibrary so buildOpenProbe
  // skips the content library path and goes straight to Haiku generation.
  const turn = await buildOpenProbe({ ...ctx, contentLibrary: undefined });

  // Override format and act to reflect this is a parallel scenario
  turn.signal.format = "PARALLEL_SCENARIO";
  turn.signal.act = "ACT_3";

  return turn;
}
